name: Frontend Test

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_HOST: ${{ secrets.AWS_HOST }}
      AWS_USER: ${{ secrets.AWS_USER }}
      AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
      AWS_FRONTEND_PATH: ${{ secrets.AWS_FRONTEND_PATH }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
